# Generated by Django 5.1.4 on 2024-12-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sql_command', models.TextField(verbose_name='Comando SQL')),
                ('result', models.TextField(blank=True, null=True, verbose_name='Resultado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
            ],
        ),
    ]
