# Generated by Django 5.1.4 on 2024-12-16 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_editor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='query',
            table='querys',
        ),
    ]
